version: 2

sources:
  - name: source_database
    database: my_database
    schema: my_schema
    tables:
      - name: my_table
        columns:
          - name: id
            tests:
              - unique
              - not_null
          - name: actor_display_login
            tests:
              - not_null
          - name: type
            tests:
              - not_null
